// Generated by BUCKLESCRIPT VERSION 1.8.0, PLEASE EDIT WITH CARE
'use strict';

var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

var x = new Date();

x.toISOString();

var data = /* int array */[
  1,
  2,
  3,
  4
];

console.log(data.filter((function (x) {
                return +(x % 2 === 0);
              })).map((function (x) {
              return Caml_int32.imul(x, x);
            })).reduce((function (x, y) {
            return x + y | 0;
          }), 0));

exports.x    = x;
exports.data = data;
/* x Not a pure module */
