// Generated by BUCKLESCRIPT VERSION 1.8.0, PLEASE EDIT WITH CARE
'use strict';

var List       = require("bs-platform/lib/js/list.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

var _notes = [/* [] */0];

function addNote(note) {
  var id = Pervasives.string_of_int(List.length(_notes[/* contents */0]) + 1 | 0);
  var newNote = /* record */[
    /* text */note[/* text */0],
    /* id */id
  ];
  _notes[/* contents */0] = Pervasives.$at(_notes[/* contents */0], /* :: */[
        newNote,
        /* [] */0
      ]);
  return newNote;
}

function getNotes() {
  return _notes[/* contents */0];
}

function deleteNote(id) {
  _notes[/* contents */0] = List.filter((function (n) {
            return +(n[/* id */1] !== id);
          }))(_notes[/* contents */0]);
  return /* () */0;
}

exports._notes     = _notes;
exports.addNote    = addNote;
exports.getNotes   = getNotes;
exports.deleteNote = deleteNote;
/* No side effect */
