// Generated by BUCKLESCRIPT VERSION 1.8.0, PLEASE EDIT WITH CARE
'use strict';

var $$Array     = require("bs-platform/lib/js/array.js");
var Js_dict     = require("bs-platform/lib/js/js_dict.js");
var Json_decode = require("bs-json/lib/js/src/json_decode.js");

function noteFromJson(json) {
  return /* record */[
          /* text */Json_decode.field("text", Json_decode.string, json),
          /* id */Json_decode.field("id", Json_decode.string, json)
        ];
}

function notesFromJson(json) {
  return Json_decode.list(noteFromJson, json);
}

function notesToJson(notes) {
  return JSON.stringify($$Array.map((function (param) {
                    var text = param[/* text */0];
                    return Js_dict.fromList(/* :: */[
                                /* tuple */[
                                  "text",
                                  text
                                ],
                                /* :: */[
                                  /* tuple */[
                                    "id",
                                    param[/* id */1]
                                  ],
                                  /* [] */0
                                ]
                              ]);
                  }), $$Array.of_list(notes)));
}

exports.noteFromJson  = noteFromJson;
exports.notesFromJson = notesFromJson;
exports.notesToJson   = notesToJson;
/* Js_dict Not a pure module */
