// Generated by BUCKLESCRIPT VERSION 1.8.0, PLEASE EDIT WITH CARE
'use strict';

var Model = require("./model.js");

console.log(Model.getNotes(/* () */0));

Model.addNote(/* record */[/* text */"lol"]);

console.log(Model.getNotes(/* () */0));

Model.addNote(/* record */[/* text */"lol2"]);

console.log(Model.getNotes(/* () */0));

Model.addNote(/* record */[/* text */"lol2"]);

console.log(Model.getNotes(/* () */0));

Model.deleteNote("1");

console.log(Model.getNotes(/* () */0));

/*  Not a pure module */
